name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Linting test
      run: |
       go version
       go get -u golang.org/x/lint/golint
       golint -set_exit_status ./...

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v -o bin/server files/cmd/server


